import Head from 'next/head';
import Header from 'src/components/Header';
import Footer from 'src/components/Footer';
import Hero from 'src/components/home/hero';
import OurApps from 'src/components/home/OurApps';
import ECommerceExp from 'src/components/home/ECommerceExp';
import Testimonial from 'src/components/home/Testimonial';
import CallToAction from 'src/components/home/CallToAction';
import styles from '../styles/Home.module.css';
import type { NextPage } from 'next';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div>
        <Hero />
        <OurApps />
        <ECommerceExp />
        {/* <EmpowerBrand /> */}
        <Testimonial />
        <CallToAction />
      </div>
      <Footer />
    </div>
  );
};

export default Home;
