import Head from 'next/head';
import Header from 'src/components/Header';
import Footer from 'src/components/Footer';
import styles from '../styles/home.module.css';

const MainLayout: React.FC = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {children}
      <Footer />
    </div>
  );
};

export default MainLayout;
